export const GetUsageCategoryRoute = 'web.accounts.usage-categories.get'
export const GetMyUsageCategoryRoute = 'web.accounts.usage-categories.my-category'
export const CreateUsageCategoryRoute = 'web.accounts.usage-categories.create'
export const UpdateUsageCategoryRoute = 'web.accounts.usage-categories.update'
export const DeleteUsageCategoryRoute = 'web.accounts.usage-categories.delete'
export const SelectUsageCategoryRoute = 'web.accounts.usage-categories.select'

export const GetPlanRoute = 'web.accounts.plans.get'
export const CreatePlanRoute = 'web.accounts.plans.create'
export const UpdatePlanRoute = 'web.accounts.plans.update'
export const DeletePlanRoute = 'web.accounts.plans.delete'

export const GetRoleRoute = 'web.accounts.roles.get'
export const CreateRoleRoute = 'web.accounts.roles.create'
export const UpdateRoleRoute = 'web.accounts.roles.update'
export const DeleteRoleRoute = 'web.accounts.roles.delete'

export const GetPermissionRoute = 'web.accounts.permissions.get'
export const AssignPermissionRoute = 'web.accounts.permissions.assign'
export const UnassignPermissionRoute = 'web.accounts.permissions.unassign'