export const LoginRoute = 'frontend.auth.login'
export const RegisterRoute = 'frontend.auth.register'
export const ForgotPasswordRoute = 'frontend.auth.forgot-password'
export const LoginGoogleRoute = 'frontend.auth.google.login'
export const AuthorizeGoogleRoute = 'frontend.auth.google.authorize'

export const LoginApiRoute = 'web.auth.login'
export const RegisterApiRoute = 'web.auth.register'
export const LogoutApiRoute = 'web.auth.logout'
export const ForgotPasswordApiRoute = 'web.auth.forgot-password'
export const ResetPasswordApiRoute = 'web.auth.reset-password'
